homepage/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.story3, name='story3'),
    path('about_me/', views.about_me, name='about_me'),
    path('gallery/', views.gallery, name='gallery'),
    
    path('schedule/', views.schedule, name='schedule'),
    path('schedule_create/', views.schedule_create, name='schedule_create'),
    path('schedule_delete/', views.schedule_delete, name='schedule_delete')

]

story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models
from datetime import datetime, timedelta

# Create your models here.


class Schedule(models.Model):

    kegiatan = models.CharField(max_length=30)
    hari = models.DateTimeField(default=datetime.now)
    waktu = models.TimeField()
    tempat = models.CharField(max_length=20)
    kategori = models.CharField(max_length=20)

    # def __str__(self):
    #     return self.activity

homepage/forms.py
from django import forms
from .models import Schedule


class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = [
         'kegiatan',
         'hari', 
         'waktu', 
         'tempat', 
         'kategori'
         ]
        widgets = {
            'hari': forms.DateInput(attrs={'type': 'date'}),
            'waktu': forms.TimeInput(attrs={'type': 'time'})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

homepage/views.py
from django.shortcuts import render, redirect
from .models import Schedule
# from .forms import ScheduleForm
from . import forms

# Create your views here.
def story3 (request):
    return render(request, 'story3.html')

def about_me (request):
    return render(request, 'about_me.html')

def gallery (request):
    return render(request, 'gallery.html')

def schedule(request):
    schedules = Schedule.objects.all().order_by('hari')
    return render(request, 'schedule.html', {'schedules': schedules})

def schedule_create(request):
    if request.method == 'POST':
        form = forms.ScheduleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('homepage:schedule')

    else:
        form = forms.ScheduleForm()
    return render(request, 'schedule_create.html', {'form': form})

def schedule_delete(request):
	Schedule.objects.all().delete()
   
	return redirect('homepage:schedule')

homepage/templates/about_me.html
<!DOCTYPE html>
{% load static %}
    <html>
      <head>
        <title> My Biography </title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/story3.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Barlow">
      </head>

      <body>
          <form action="{% url 'homepage:story3' %}">
              <button class="btn" type="submit">BACK</button>
          <div class="headeraboutme">
              <div class="judulaboutme"><h1>STEFAN SAGALA</h1>
              </div>
              <br>
              <p class="font">I am capable to write in English and Bahasa Indonesia. <br>
                I am also capable to code in Python and Java. </p>
              <img class="imgprof" src = "{% static 'images/quanta.jpg' %}" height = 200 width = 200 align="center"> </img>
          </div>
    
        <div class="content">
        <div class="font">

          <div class="box" style="background-color:#765C34">
                <p>My name is Stefan Kenichi <br> Soaloon Sagala. My friends <br> usually call me Stefan. I am <br> creative and I consider 
                    <br> myself as a perfectionist. <br> Ironically, I don’t really <br> depend on the result of <br> every work I do. Instead, I  
                    <br> love analyzing myself <br> growing through the <br> process of learning and <br> making. </p>
          </div>

          <div class="box" style="background-color:#A77427">
                <p>STUDY</p>
                <p><strong>Information System</strong></p>
                <p>UNIVERSITY</p>
                <p><strong>University of Indonesia</strong></p>
                <p>BATCH</p>
                <p><strong>2018</strong></p>
                <p>STUDENT NUMBER</p>
                <p><strong>1806191465</strong></p>
          </div>

          <div class="box" style="background-color: #C78726">
                <p>INTEREST
                        <ul class="daftar">
                        <li>MUSIC</li>
                        <li>CONCERTS</li>
                        <li>CREATIVE WORKING</li>
                        <li>BOOKS</li>
                        <li>MOVIES</li>
                        </ul>
                        </p>
          </div>

          <div class="box" style="background-color: #634415">
                  <p> HOBBIES 
                    <ul class="daftar">
                    <li>listening to the music</li> 
                    <li>going to music shows</li> 
                    <li>traveling</li>
                    <li>strolling around</li>
                    <li>sleeping</li>
                    <li>reading books</li>
                    <li>writing</li> 
                    <li>watching movies</li>
                    </ul> 
                  </p>
          </div>

        </div>
        </div>
      </body>
    </html>

homepage/templates/formfix.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel= "stylesheet" href= "/static/bootstrap.min.css">
  <link rel= "stylesheet" href= "/static/formulir.css">
   <link href="formulir.css" rel="stylesheet" type="text/css" />
   
  
<!-- <title></title> -->
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand"  href="/">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/experiences">Experiences<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/gallery">Gallery</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/addSchedule">add Schedule</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/listSchedule">My Scedule</a>
      </li>
     
    </ul>
  </div>
</nav>  







<div class="container-fluid">
  <div class="row justify-content-center">
  <div class="row">
      <section name="form">
      <br>
      <h2> CREATE SCHEDULE </h2>
      <br>
      <br>
      <form id="form" method="POST" action = "saveschedule">
      <input type="hidden" name="csrfmiddlewaretoken" value="PXw4RorlLIwe2P2Pht5zPe0PZykJ0raDzzwFkPDozgpApQaCehogfJsZI7FIBLFx">
      <tr><th><label for="id_activity">activity:</label></th><td><input type="text" name="activity" class="form-control" maxlength="90" required id="id_activity"></td></tr>
<tr><th><label for="id_place">Place:</label></th><td><input type="text" name="place" class="form-control" required id="id_place"></td></tr>
<tr><th><label for="id_date">Date:</label></th><td><input type="date" name="date" value="2019-10-07 00:00:00" class="form-control" required id="id_date"></td></tr>
<tr><th><label for="id_time">Time:</label></th><td><input type="time" name="time" value="2019-10-07 00:00:00" class="form-control" required id="id_time"></td></tr>
<tr><th><label for="id_description">Description:</label></th><td><textarea name="description" cols="40" rows="10" class="form-control" required id="id_description">
</textarea></td></tr> 
      <br>
      <button type="submit" class="btn btn-primary"> Add Schedule </button>
      </form>
      </section>

    
  </div>
  </div>
</div>
   
</body>
</html>

homepage/templates/formulir.html
<!DOCTYPE html>
<html>
<head>
    <title> SCHEDULE </title>
    <link rel="stylesheet" type="text/css" href="story3.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>  
        <div class="penjelasan">
            <h1>WEEKLY SCHEDULE</h1>
            <p>Fill the form below to set up your weekly schedule</p>
        </div>
        <div class="formulirnya">
            
            <form action="formulirhasil.html" target="_blank" method="POST">
            <br> <br> <br>
            <!-- HARI:<br> -->
            <!-- <select name="hari">
                    <option value="Senin">Senin</option>
                    <option value="Selasa">Selasa</option>
                    <option value="Rabu">Rabu</option>
                    <option value="Kamis">Kamis</option>
                    <option value="Jumat">Jumat</option>
                    <option value="Sabtu">Sabtu</option>
                    <option value="Minggu">Minggu</option>
            </select> -->
            <!-- <br><br> -->
            TANGGAL:<br>
            <input type="datetime-local" name="tanggal">
            <br>
            JAM: <br>
            <input type="time" name="jam">
            <br>
            KEGIATAN: <br>
            <input type="text" name="kegiatan" >
            <br>
            TEMPAT: <br>
            <input type="text" name="tempat">
            <br>
            KATEGORI: <br>
            <input type="radio" name="kategori" value="akademis" checked> Akademis<br>
            <input type="radio" name="kategori" value="nonakademis"> Nonakademis<br>
            
            <p>Thank you for submitting. <br> Click the button below to see your schedule.</p>
            <!-- <form action = url (story3.html)> -->
            <!-- <button class="btn" type="submit">Buat Jadwal</button> -->
            <button onclick="jadwal()">Buat Jadwal</button>
            </form>
        </div>    
    
</body>
</html>

homepage/templates/formulirhasil.html
<!DOCTYPE html>
<html>
<head>
    <title> STEFAN SAGALA </title>
    <link rel="stylesheet" type="text/css" href="story3.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>  
<script>
function jadwal(){
    <div class="penjelasan">
        <h1>WEEKLY SCHEDULE</h1>
        <p>This is your schedule.</p>
    </div>
    <div class="formulirnya">

  <table style="width:100%">
    <tr>
    <th>Tanggal</th> 
    <th>Jam</th>
    <th>Kegiatan</th>
    <th>Tempat</th>
    <th>Kategori</th>
    </tr>
    <tr>
    <td></td>
    <td></td>
    <td></td>
    </tr>
    <tr>
    <td></td>
    <td></td>
    <td></td>
    </tr>
    <tr>
    <td></td>
    <td></td>
    <td></td>
    </tr>
  </table>  
  
  </div>
}
</script>
</body> 

homepage/templates/gallery.html
<!DOCTYPE html>
{% load static %}
    <html lang="en">
       
      <head>
        <title> Gallery </title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'css/story3.css' %}">
        <!-- <link rel="stylesheet" href="bootstrap.min.css"> -->
        <link href="https://fonts.googleapis.com/css?family=Playfair+Display|Rock+Salt|Rufina|Ruthie|Stardos+Stencil&display=swap" rel="stylesheet">
      </head>

      <body>
      <div class="bodygallery">
      <form action="{% url 'homepage:story3' %}">
      <button class="btn" type="submit">BACK</button>
      <div class="row">
            <div class="column">
                <img src="{% static 'images/indie1.jpg' %}">
                <img src="{% static 'images/indie2.jpg' %}">
                <img src="{% static 'images/indie3.jpg' %}">
            </div>
            <div class="column">
                <img src="{% static 'images/indie4.jpg' %}">
                <img src="{% static 'images/indie5.jpg' %}">
                <img src="{% static 'images/indie6.jpg' %}">
            </div>
            <div class="column">
                <img src="{% static 'images/indie7.jpg' %}">
                <img src="{% static 'images/indie8.jpg' %}">
                <img src="{% static 'images/indie9.jpg' %}">
            </div>
            <div class="column">
                <img src="{% static 'images/indie10.jpg' %}">
                <img src="{% static 'images/indie11.jpg' %}">
                <img src="{% static 'images/indie12.jpg' %}">
            </div>
            <div class="column">
                <img src="{% static 'images/indie13.jpg' %}">
                <img src="{% static 'images/indie14.jpg' %}">
                <img src="{% static 'images/indie15.jpg' %}">
            </div>
            <div class="column">
                <img src="{% static 'images/indie16.jpg' %}">
                <img src="{% static 'images/indie17.jpg' %}">
                <img src="{% static 'images/indie18.jpg' %}">
            </div>
            <div class="column">
                <img src="{% static 'images/indie19.jpg' %}">
                <img src="{% static 'images/indie20.jpg' %}">
                <img src="{% static 'images/indie21.jpg' %}">
            </div>
            <div class="column">
                <img src="{% static 'images/indie22.jpg' %}">
                <img src="{% static 'images/indie23.jpg' %}">
                <img src="{% static 'images/indie24.jpg' %}">
            </div>
          </div>

      </div>
          </body>
      </html>

homepage/templates/schedule.html
<!DOCTYPE html>
<html>
	{% load static %}
	 <meta name="viewport" content="width=device-width, initial-scale=1.0">
	 <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet"> 
     <link rel="stylesheet" type="text/css" href="{% static 'css/story3.css' %}"> 
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
     
	 <!-- <link rel="stylesheet" href={% static 'css/bootstrap.css' %}>
	 <link rel="stylesheet" href={% static 'css/bootstrap.min.css' %}>
	 <link rel="stylesheet" href={% static 'js/bootstrap.js' %}>
     <link rel="stylesheet" href={% static 'js/bootstrap.min.js' %}> -->
     
	 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<head>
	<title>Create Schedule</title>
</head>
<body class="bodyformulir2">
    <!-- {% block content %} -->
    <div class="paragprah">
    <h1 class="d-flex align-items-center justify-content-center">My Schedule</h1>
    <div class="article">
        <div class="d-flex align-items-center justify-content-center">
            <a href="{% url 'homepage:schedule_create' %}"><button type="button" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-pencil"></span> 
                Add Schedule
                </button></a>
            <a href="{% url 'homepage:schedule_delete' %}">
                <button type="button" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-trash"></span> 
                Reset Data
                </button>
            </a>
        </div>
        <!-- <div class="boxform" style="background-color:black"> -->
        <div class="jadwal">
        <div class="article">
            <div class="row">
                {% for schedule in schedules %}

                    <div class="col-sm-4 text-center">
                        <h2 class="act">{{ schedule.kegiatan }}</h2>
                        <p>{{ schedule.hari }}<br>
                            {{ schedule.waktu }}<br>
                            {{ schedule.tempat }}<br>
                            {{ schedule.kategori }}</p>
                    </div>

                {% endfor %}
            </div>
        </div>
        </div>
        <!-- </div> -->
    </div>
    </div>
    <!-- {% endblock %} -->
    </div>
    
</body>
</html>

homepage/templates/schedule_create.html
<!DOCTYPE html>
<html>
	{% load static %}
	 <meta name="viewport" content="width=device-width, initial-scale=1.0">
	 <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet"> 
     <link rel="stylesheet" type="text/css" href="{% static 'css/story3.css' %}"> 
	 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
     
     <!-- <link rel="stylesheet" href={% static 'css/bootstrap.css' %}>
	 <link rel="stylesheet" href={% static 'css/bootstrap.min.css' %}>
	 <link rel="stylesheet" href={% static 'js/bootstrap.js' %}>
     <link rel="stylesheet" href={% static 'js/bootstrap.min.js' %}> -->
     
	 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<head>
	<title>Schedules</title>
</head>
<body class="bodyformulir">
		<div class="boxform" style="background-color:black">
	<div class="jadwal">
	<div style="padding-left:5%;padding-right:5%;">
        <h1 class="d-flex align-items-center justify-content-center" >Add Schedule</h1>
        {% block content %}

        <form method="POST" class="post-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Submit</button>
        </form>

    {% endblock %}

	</div>
	</div>
</body>
</html>

homepage/templates/story3.html
<!DOCTYPE html>
{% load static %}
    <!-- <html lang="en"> -->
      <head>
        <title> STEFAN SAGALA </title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'css/story3.css' %}">
        <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
        <link href="https://fonts.googleapis.com/css?family=Playfair+Display|Rock+Salt|Rufina|Ruthie|Stardos+Stencil&display=swap" rel="stylesheet">
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script> -->
      
      
      </head>

      <body>
          <div class="bodystory">

            <h3 class="header" id="header1">MEET</h3>
            <h2 class="header" id="header2">STEFAN <br> SAGALA</h2>
              <p id="clickAboutMe">
                <a href="{% url 'homepage:about_me' %}" class="click">ABOUT ME</a>
              </p>
              <p id="clickGallery">
                <a href="{% url 'homepage:gallery' %}" class="click">GALLERY</a>
              </p>

              <p id="clickFormulir">
                <a href="{% url 'homepage:schedule' %}" class="click">FORM</a>
              </p>
    
              <img src="{% static 'images/spotify.png' %}" class="logo" id="logoSpotify"> </img>
              <img src="{% static 'images/ig.png' %}" class="logo" id="logoInstagram"> </img>
              <img src="{% static 'images/linkedin.png' %}" class="logo" id="logoLinkedIn"> </img>
              <img src="{% static 'images/twitter.png' %}" class="logo" id="logoTwitter"> </img>
    
              <p class="nama" id="namaSpotify">Stefan Sagala</p>;
              <p class="nama" id="namaInstagram">@iisbon</p>
              <p class="nama" id="namaLinkedIn">Stefan Sagala</p>
              <p class="nama" id="namaTwitter">@anaklndie</p>
    
              <img src="{% static 'images/logoku.jpeg' %}" class="logoku"></img>
               
        </div>
      </body>